#Generated with the help of:
# cat traits.csv | awk -F , '{printf "'\''%s'\'':('\''%s'\'',float,'description','group'),\n ", $1, $1}'
attributes = {
      'circle ratio': ('CIR_RATIO',float,'description','Computation'),
      'x pixel':('X_PIXEL',float,'description','Computation'),
      'y pixel':('Y_PIXEL',float,'description','Computation'),
      'xScale':('X_SCALE',float,'description','Computation'),
      'yScale':('Y_SCALE',float,'description','Computation'),
      'computation time':('COMP_TIME',float,'description','Computation'),
      'Skeleton Vertices':('SKL_NODES',float,'description','Computation'),
      'DIA_STM':('DIA_STM',float,'description','Common Traits'),
      'DIA_STM_SIMPLE':('DIA_STM_SIMPLE',float,'description','Common Traits'),
      'AREA':('AREA',float,'description','Common Traits'),
      'AVG_DENSITY':('AVG_DENSITY',float,'description','Common Traits'),
      'TD_MED':('TD_MED',float,'description','Common Traits'),
      'TD_AVG':('TD_AVG',float,'description','Common Traits'),
      'WIDTH_MED':('WIDTH_MED',float,'description','Common Traits'),
      'WIDTH_MAX':('WIDTH_MAX',float,'description','Common Traits'),
      'D10':('D10',float,'description','Common Traits'),
      'D20':('D20',float,'description','Common Traits'),
      'D30':('D30',float,'description','Common Traits'),
      'D40':('D40',float,'description','Common Traits'),
      'D50':('D50',float,'description','Common Traits'),
      'D60':('D60',float,'description','Common Traits'),
      'D70':('D70',float,'description','Common Traits'),
      'D80':('D80',float,'description','Common Traits'),
      'D90':('D90',float,'description','Common Traits'),
      'DS10':('DS10',float,'description','Common Traits'),
      'DS20':('DS20',float,'description','Common Traits'),
      'DS30':('DS30',float,'description','Common Traits'),
      'DS40':('DS40',float,'description','Common Traits'),
      'DS50':('DS50',float,'description','Common Traits'),
      'DS60':('DS60',float,'description','Common Traits'),
      'DS70':('DS70',float,'description','Common Traits'),
      'DS80':('DS80',float,'description','Common Traits'),
      'DS90':('DS90',float,'description','Common Traits'),
      'RDISTR_X':('RDISTR_X',float,'description','Common Traits'),
      'RDISTR_Y':('RDISTR_Y',float,'description','Common Traits'),
      'SKL_DEPTH':('SKL_DEPTH',float,'description','Common Traits'),
      'SKL_WIDTH':('SKL_WIDTH',float,'description','Common Traits'),
      'RTP_COUNT':('RTP_COUNT',float,'description','Common Traits'),
      'ANG_TOP':('ANG_TOP',float,'description','Monocot Root Traits'),
      'ANG_BTM':('ANG_BTM',float,'description','Monocot Root Traits'),
      'STA_RANGE':('STA_RANGE',float,'description','Dicot Root Traits'),
      'STA_DOM_I':('STA_DOM_I',float,'description','Dicot Root Traits'),
      'STA_DOM_II':('STA_DOM_II',float,'description','Dicot Root Traits'),
      'STA_25_I':('STA_25_I',float,'description','Dicot Root Traits'),
      'STA_25_II':('STA_25_II',float,'description','Dicot Root Traits'),
      'STA_50_I':('STA_50_I',float,'description','Dicot Root Traits'),
      'STA_50_II':('STA_50_II',float,'description','Dicot Root Traits'),
      'STA_75_I':('STA_75_I',float,'description','Dicot Root Traits'),
      'STA_75_II':('STA_75_II',float,'description','Dicot Root Traits'),
      'STA_90_I':('STA_90_I',float,'description','Dicot Root Traits'),
      'STA_90_II':('STA_90_II',float,'description','Dicot Root Traits'),
      'RTA_DOM_I':('RTA_DOM_I',float,'description','Dicot Root Traits'),
      'RTA_DOM_II':('RTA_DOM_II',float,'description','Dicot Root Traits'),
      'STA_MIN':('STA_MIN',float,'description','Dicot Root Traits'),
      'STA_MAX':('STA_MAX',float,'description','Dicot Root Traits'),
      'STA_MED':('STA_MED',float,'description','Dicot Root Traits'),
      'RTA_RANGE':('RTA_RANGE',float,'description','Dicot Root Traits'),
      'RTA_MIN':('RTA_MIN',float,'description','Dicot Root Traits'),
      'RTA_MAX':('RTA_MAX',float,'description','Dicot Root Traits'),
      'RTA_MED':('RTA_MED',float,'description','Dicot Root Traits'),
      'NR_RTP_SEG_I':('NR_RTP_SEG_I',float,'description','Dicot Root Traits'),
      'NR_RTP_SEG_II':('NR_RTP_SEG_II',float,'description','Dicot Root Traits'),
      'ADVT_COUNT':('ADVT_COUNT',float,'description','Dicot Root Traits'),
      'BASAL_COUNT':('BASAL_COUNT',float,'description','Dicot Root Traits'),
      'ADVT_ANG':('ADVT_ANG',float,'description','Dicot Root Traits'),
      'BASAL_ANG':('BASAL_ANG',float,'description','Dicot Root Traits'),
      'HYP_DIA':('HYP_DIA',float,'description','Dicot Root Traits'),
      'TAP_DIA':('TAP_DIA',float,'description','Dicot Root Traits'),
      'MAX_DIA_90':('MAX_DIA_90',float,'description','Dicot Root Traits'),
      'DROP_50':('DROP_50',float,'description','Dicot Root Traits'),
      'CP_DIA25':('CP_DIA25',float,'description','Dicot Root Traits'),
      'CP_DIA50':('CP_DIA50',float,'description','Dicot Root Traits'),
      'CP_DIA75':('CP_DIA75',float,'description','Dicot Root Traits'),
      'CP_DIA90':('CP_DIA90',float,'description','Dicot Root Traits'),
      'NODAL_LEN':('NODAL_LEN',float,'description','Excised Root Traits'),
      'NODAL_AVG_DIA':('NODAL_AVG_DIA',float,'description','Excised Root Traits'),
      'LT_BRA_FRQ':('LT_BRA_FRQ',float,'description','Excised Root Traits'),
      'LT_AVG_LEN':('LT_AVG_LEN',float,'description','Excised Root Traits'),
      'LT_AVG_ANG':('LT_AVG_ANG',float,'description','Excised Root Traits'),
      'LT_ANG_RANGE':('LT_ANG_RANGE',float,'description','Excised Root Traits'),
      'LT_MIN_ANG':('LT_MIN_ANG',float,'description','Excised Root Traits'),
      'LT_MAX_ANG':('LT_MAX_ANG',float,'description','Excised Root Traits'),
      'LT_DIST_FIRST':('LT_DIST_FIRST',float,'description','Excised Root Traits'),
      'LT_MED_DIA':('LT_MED_DIA',float,'description','Excised Root Traits'),
      'LT_AVG_DIA':('LT_AVG_DIA',float,'description','Excised Root Traits'),
  }

def initial(value):
    if(value == "Common Traits"):
        return True
    return False

s = "{\n"
for key,value in sorted(attributes.items(), key=lambda (k,v): v[3]):
    s = s + """'%s':{
            'field': '%s',
            'type': float,
            'initial': %r,
            'description': '%s',
            'group':'%s',
            'name': '%s'
        },
        """%(key,value[0],initial(value[3]),value[2],value[3],key)
s  = s + "}"
print(s)
