- Air temperature
- Organ temperature
- Change over the course of experiment
- Photon flux density (PPFD) measured at plant or canopy level
- Average length of the light period
- Light intensity
- Fraction of outside light intercepted by growth facility components and surrounding structures
- Type of lamps used
- R/FR ratio
- Daily UV-A radiation
- Daily UV-B radiation
- Total daily irradiance
- Atmospheric CO2 concentration
- Average CO2 during the light and dark periods
- Vapour pressure deficit
- Average relative humidity during the light period
- Average VPD during the dark period
- Average relative humidity during the dark period
- Rooting medium
- Container type
- Container volume
- Container height
- Number of plants per containers
- Plot size
- Sowing density
- Rooting medium replenishment
- Soil pH
- Porosity
- Medium temperature
- Soil penetration strength
- Water retention capacity
- Organic matter content
- Medium composition
- Extractable N content per unit ground volume before fertilizer added
- Type and amount of fertilizer added per container
- Nutrient concentration per unit ground area at the end of the experiment
- Volume and timing of water added per container
- Matrix potential
- Watering regimen
- Composition of nutrient solutions used for irrigation
- Electrical conductivity