name: Release Python SDK
on:
  release:
    branches:
      - master
jobs:
  publish:
    name: Build & publish package to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Cache Python
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-3.8-pip-${{ hashFiles('setup.cfg') }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install .
          pip install flake8 pytest coveralls setuptools wheel twine
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/*